### ISSUE TITLE
Missing plot scripts

### ISSUE THREAD

**Issue by dietmarw** [ALSETLab/Modelica-Drone-3D-FMI#37]
The library contains several commands that are pointing to plot scripts that are missing.

**Comment by mpodlaski** [comment]
Added scripts back into library in 8e6c491f640f46318c6b20d377b5a13aba953f52

**Comment by dietmarw** [comment]
Unfortunately, the scripts were placed on the top level of the repo. Unreachable for the Modelica tools since outside the package. The proper place to store those non-modelica files is under `Resources/Scripts/`  and also point to them using `modelica://` URIs. This was done in 924a4670807b90419cf69af692cf7c124140d626

Mind the script `drone_simulation_setup.mos` is only mentioned in the README and not part of any command. And the script `plotOutput.mos` is not mentioned anywhere and not used anywhere. So what is the purpose of this?

**Comment by dietmarw** [comment]
There is still one script missing: ` animate_gyroscope.mos`

Can you add this in the correct location and also link correctly (see above)?

**Comment by mpodlaski** [comment]
- ok thank you for moving the scripts!
- plotOutputs.mos generates a standardized plot of the XYZ location of the drone when running the test cases, it needs to be added to the readme when I update it. 
- I removed the gyroscope package. It was also test files copied from another library, which is why we didn't have the .mos file in the place. The models are not used anywhere else in the library nor add any value to the library as it is now, so they can be removed. (done in 5c6a5cbcc63b1dff0279dbfa475be7ba037794c6 )
