### ISSUE TITLE
Errors when running the Example model.

### ISSUE THREAD

**Issue by noahmartinwilliams** [ALSETLab/Modelica-Drone-3D-FMI#51]
On Modelica v1.25.0 when I try to run the TestSystem for the DroneWithIdealPower example it gives me this:

```
[1] 21:10:48 Translation Error
[/home/noah/src/package-sources/OpenModelica/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 342:7-342:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed
variables:
  
equations:
  drone.droneChassis1.bodyCylinder.body.frame_a.r_0[1] = drone.propellerRev.blades.bodyShape4.body.frame_a.r_0[1] + 0.25 * drone.accelerometer.relativeAngles.R_rel.T[2,1]

[2] 21:10:48 Translation Error
[/home/noah/src/package-sources/OpenModelica/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 346:7-346:90]: Internal error function analyseStrongComponentBlock failed

[3] 21:10:48 Translation Error
[/home/noah/src/package-sources/OpenModelica/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 196:5-196:89]: Internal error function analyseStrongComponentScalar failed

[4] 21:10:48 Translation Error
[/home/noah/src/package-sources/OpenModelica/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 107:7-107:113]: Internal error function strongComponentsScalar failed (sorting strong components)

[5] 21:10:48 Translation Error
[/home/noah/src/package-sources/OpenModelica/OMCompiler/Compiler/BackEnd/BackendDAEUtil.mo: 8012:5-8012:89]: Internal error Transformation module sort components failed
```

I honestly don't know enough about Modelica to know how to fix this, so it might be something wrong with Modelica, but I suspect that this project is out of date. :/

**Comment by dietmarw** [comment]
Hi, first just a bit of background information. [Modelica](https://specification.modelica.org/) is a modelling **language** developed by the [Modelica Association](https://modelica.org/). The Modelica Association also develops and maintains the [Modelica Standard Library](https://github.com/modelica/ModelicaStandardLibrary) which basically is a  collection fundamental models from the different domains leveraging the Modelica modelling language.

Now in order to work with Modelica models you still need a tool. There are several[ Modelica tools](https://modelica.org/tools/) available (both commercial and open-source). When you refer to "Modelica v1.25" then you most likely mean you tried the Drone library with the [OpenModelica tool](https://openmodelica.org/) v1.25.0-dev (the final version is not yet released). 

OK now back to your problem. The thing is, this library was developed with the commercial tool Dymola and makes use of some Modelica features that most likely are not (yet) supported by the latest OpenModelica version. Hence you get the error message. There might be other models within this drone library that will work just fine (but I have not tested this) and we have no plans as of now to especially adapt this library to OpenModelica.

It's probably not the answer you were hoping for but that is basically the situation.
